name: Build and Deploy To Non-Prod

on: 
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 'Enter branch or commit to checkout'
      environment:
        type: environment
        required: true
        description: 'environment to run'
        default: nonprod 
        
env:
  REGISTER_SERVER: ftrContainerRepo.azurecr.io

jobs:
  docker:
    name: "Build and store Docker image"
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}
    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v2
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTER_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build docker  image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.REGISTER_SERVER }}/${{ github.repository }}:${{ github.event.inputs.environment}}.${{ github.sha }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max       

    # - uses: ./.github/actions/Build-Publish-Docker
    #   with:
    #    azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    #    registry_server: ftrContainerRepo.azurecr.io
    #    registry_username: ${{ secrets.REGISTRY_USERNAME }}
    #    registry_password: ${{ secrets.REGISTRY_PASSWORD }}  
    #    environment: ${{ env.environment }}

  manage_infrastructure:
    name: manage_infrastructure
    runs-on: ubuntu-latest
    needs: docker
    env:
      TF_WORKSPACE: "code-push-server-${{ github.event.inputs.environment }}"
      TF_IN_AUTOMATION: true
      name:  ${{github.event.inputs.environment}}
    defaults:
      run:
        working-directory: ./terraform  
    permissions:
      contents: read 
    steps: 
    - name: Code checkout    
      uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}   
    - name: Setup Terraform  
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}    
    - name: Initialise Terraform
      run: terraform init 
    - name: Apply Terraform
      run: terraform apply var environment=${{ github.event.inputs.environment }} -input=false -auto-approve 
    - name: Azure logout   
      run: az logout
      shell: bash
      if: always()  
     

  Deploy:
    runs-on: ubuntu-latest
    needs: [ docker, manage_infrastructure]
    environment:  ${{github.event.inputs.environment}}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'codepush-server-app-${{ github.event.inputs.environment }}'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          image: ${{ env.REGISTER_SERVER }}/${{ github.repository }}:${{ github.event.inputs.environment}}.${{ github.sha }}:latest



      
 

  
    

  
                
          
     
    
             
 

    
